### ISSUE TITLE
Empty close reasons

### ISSUE THREAD

**Issue by edreal** [uNetworking/uWebSockets#1025]
When websocket gets closed because of maxPayloadLength exceeded, it closes with 1006 and empty reason data.

Would it be possible to have option to turn on details for close reasons?

I would like to monitor socket closes also log if someone gets disconnected for exceeded payload length to know that there is something wrong client side and its sending unexpected sized messages or in case of attempted DoS attack etc.

I could also do this on message handler but would that be good idea?

Thanks

**Comment by alexhultman** [comment]
There are better close codes we can use (standard):

1009 | Message too big | The endpoint is terminating the connection because a data frame was received that is too large.
-- | -- | --

**Comment by edreal** [comment]
Oh yeah, looks like that would suit the purpose.

**Comment by alexhultman** [comment]
Too bad the execution path does not allow passing custom data like that, we only trigger a close, then close handler has a hard-coded 1006 for all force closes. This would have to be fixed in uSockets.

**Comment by alexhultman** [comment]
us_socket_close would have to pass void *user, probably. Then we could start putting more meaningful close reasons

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uSockets/issues/110

**Comment by alexhultman** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

I'm interested in this. There should be at least five different reasons for internal close

**Comment by alexhultman** [comment]
You can use close code 3000 as a library reserved together with custom text, because that code cannot be sent

**Comment by alexhultman** [comment]
Oh, I see now. You can't really use any code other than 1006 like we already do, because that's the only code that the other end MUST NOT send as code (well, 1005 also) - 1006 is a pseudo code that can **only** be reported from the library itself. That's why we only report that code. Reporting 1009 as an internal code is wrong, since that overlaps with the possibility of the other end actually sending 1009 themselves.

So what we can do is we can report 1006 with a varying string message like "Message too big", etc. So it becomes a debug feature in English text. We can do that

**Comment by alexhultman** [comment]
Alright this is fixed now
