### ISSUE TITLE
UWS_HTTPRESPONSE_NO_WRITEMARK Needs be defaulted to false for security reasons (Fingerprinting)

### ISSUE THREAD

**Issue by Phara0h** [uNetworking/uWebSockets#1040]
`UWS_HTTPRESPONSE_NO_WRITEMARK` Needs be defaulted to false due to security reasons or simply removed (increased performance). You do not want to let your client know what version and server you are using. This gives them free information about your server to make it easier to target specific attacks geared towards it. 

[OWASP Fingerprinting](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server)

**Comment by Phara0h** [comment]
@alexhultman-2fa Going to explain why you are ignoring security issues?

**Comment by alexhultman-2fa** [comment]
Nobody is going to listen to you if you go all egotistical maniac about it - some humbleness and understanding of others would take you a lot further. One good start is to move away from the requiring-demanding-threatening model and go with the ask-propose-recommend model. It's all in the wording and "svansföring". You act like the typical clown as described in my "Read this before posting" issue. You're sabotaging yourself like this and the only reason why I haven't banned you and deleted these duplicates is because I'm genuinely fascinated with your social display. Look at how others talk, see where that leads them. I've been doing this for four years and I've stumbled upon many, many carbon copies of you before. They all get the same treatment. You are in no position to demand anything, and acting like a clown is not going to lead you anywhere.
