### ISSUE TITLE
Support of Cmake.

### ISSUE THREAD

**Issue by patriotyk** [uNetworking/uWebSockets#1043]
Adding support of CMake, adds possibility to easily integrate uWebSockets to other C++ projects. 

For my project I wrote small CMakeLists.txt for uWebSockets and it works very well. So If maintainer of project agrees to add Cmake support I could prepare PR.

**Comment by alexhultman-2fa** [comment]
No thank you. Anything "build system" is unnecessary friction and nobody will ever agree on anything. We use 1970s Makefile because it does the job and has done for 5 decades.

**Comment by shimondoodkin** [comment]
it is not about build-systems debate, it is about integration, - allows people to use it.
people ask themselves how to plug this into any test project on windows, a: let's use make, it knows to generate vc++ projects. or better let's use vcpkg it will download all dependencies, but then how...

I solved it by:

C:\vcpkg\vcpkg.exe install uwebsockets --triplet x64-windows

and CMakeLists.txt file (only relevant basics are here):

cmake_minimum_required(VERSION 3.9)

set(CMAKE_TOOLCHAIN_FILE "C:/vcpkg/scripts/buildsystems/vcpkg.cmake")

project(app)
set(CMAKE_CXX_STANDARD 20)     

find_package(ZLIB REQUIRED)
find_library(USOCKETS_LIB uSockets)
find_package(unofficial-libuv CONFIG REQUIRED)
find_library(LIBUV_LIB libuv)


find_path(UWEBSOCKETS_INCLUDE_DIR uwebsockets)
include_directories(${UWEBSOCKETS_INCLUDE_DIR})

add_executable(app app.cpp)

# in vcpkg only on windows package uwebsockets is installed with libuv

target_link_libraries(app PRIVATE
ZLIB::ZLIB
 ${USOCKETS_LIB}
 ${LIBUV_LIB}
)

**Comment by xarthurx** [comment]
@alexhultman-2fa 
It will also gain popularity among the young generation as they usually start cpp with CMake.
Uneasy integration of the lib will also make them turn to other libs...

**Comment by alexhultman** [comment]
It's ultimately a problem of time and energy.

I did have CMake in this project 5 years ago, and I did deal with all the dissatisfied people constantly making changes to the CMake-files becuase "they needed to".

Since I removed CMake I have stopped getting tons and tons of PR only about CMake. And when you have CMake you get a lot of people saying that you should have Meson, and Bazel and whatnot.

Problem is that I simply do not have time to deal with this shit. If you can't infer how to compile a header-only standards compliant project you're not the intended audience anyways.

If you want to make a test - add CMake and maintain it - see how that goes. If you want to deal with all the shit that comes with it.

**Comment by alexhultman** [comment]
The problem is also that I've used CMake on Windows since pretty much it was created way back, and I have ALWAYS been greatly dissatisfied with it. C++ development on Windows is and has always been horrible in that regard.

Makefiles work really well on Linux and macOS and other Unix-like systems and those are pretty much the only platforms I care about anyways so I don't care about Windows being impossible without CMake. It's a non-issue.

**Comment by alexhultman** [comment]
Then you have the problem of CMake abstracting the compiler and wrapping important flags into their own flags, often times putting many years of delay on new flags that are brand new. I remember once where a bug in CMake made it impossible to perform a certain thing for many many months. It's a wrapper that's distancing you from the compiler and it is the complete opposite of where I stand. A developer should be one with his compiler and know it intimately.

CMake is literally complete shit.

**Comment by shimondoodkin** [comment]
did you understand that there is a working CMake file for this?

**Comment by xarthurx** [comment]
OK, this is a fair-enough answer.
As I'm mainly developing Windows, I guess I'm not among the intended audience of this library.
I think CMake system has improved a lot during the past 5 years, and becomes almost a standard for cross-platform stuffs.

so if you, in the future, have any interest in making this lib more cross-platform, give it a try, if possible.

In the meantime, thank you for your time and answer.

**Comment by alexhultman** [comment]
I swapped from Windows to Linux in 2006 for doing C++ development and the difference in developer experience is jaw dropping. Microsoft's tools are exactly like Internet Explorer - they don't follow standards and they suck the most of all vendors.

Clang on Linux with proper tools like AddressSanitizer is the way to go. Then you can get rid of half-assed wrappers like CMake.

**Comment by alexhultman** [comment]
> find_package(ZLIB REQUIRED)

Finding a package is a Windows-only problem. On Unix you have packages in /usr/include or maybe in /usr/local/include. That's it.

**Comment by shimondoodkin** [comment]
in linux you have pkg-config too

**Comment by alexhultman** [comment]
Look at this
https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake

A bunch of Microsoft Windows shit Program files and C:/ crap for trying to find Zlib. And it doesn't even find C:/Zlib which is where the official installer puts it. So it fails to even perform its very purpose. And you want me to add this crap? Never.

**Comment by shimondoodkin** [comment]
hehe yes it is an old problem

**Comment by xarthurx** [comment]
Check ‘vcpkg’ please.

**Comment by shimondoodkin** [comment]
vcpkg works I used uWebSockets from vcpkg

**Comment by inaryart** [comment]
I don’t recommend any build system, but what I want to say is that I can’t find a one-click compilation method. I have failed many times. I believe that many people repeat this failure, but there is no silence and choose to give up.

**Comment by alexhultman** [comment]
If one click is all the attention you are willing to invest in this project then you clearly do not fall in the category of "audience".

I can clone this lib on Linux and Mac, hit "make" and have example binaries compiled and working within a minute.

Whether we provide a plugin to your Tamagochi set up or not is irrelevant, you as user are encouraged to set up whatever build system you need to solve your problems.

**Comment by eli-schwartz** [comment]
I would never recommend cmake myself, either -- a turing-complete program just for figuring out the correct `$CXXFLAGS $LDFLAGS`? What the heck.

However, this project's own Makefile seems to indicate you need `-pthread`, `-lz`, and the uSockets.a installed by the project available as a git submodule, in order to successfully link the example applications. Looking at the actual headers, `<thread>` and `<libusockets.h>` are unconditionally required, `<zlib.h>` is required if you don't pass certain defines to disable it, so... seems reasonable that you do need it.

A simple `key: value` pkg-config text file exposes exactly that for people who have done `make install`, and pkg-config is the unix standard. It has a defined unixy location to search for the file. It's trivially usable from any build system -- Makefiles, autotools, waf, scons, meson, ***even cmake*** (though cmake makes it really complicated to use for bizarre reasons). If Tamagochis don't support pkg-config already, it would be trivial to add support (may need to speak to the Tamagochi developers).
You can even use pkg-config on Windows, but you'll need to set up a global search path for pkg-config; still, that's not a bad investment, because you consolidate knowledge of installed libraries in one place. Windows package managers like conan can automate this for you, or so I've heard.

So that seems like a reasonable thing to add -- switching build systems, less so. Make is a perfectly reasonable build system if you don't need to do anything complicated, and the world is full of Makefile-using projects.

**Comment by ariestav** [comment]
@shimondoodkin Were you ever able to get uWebSockets statically linked to your Visual Studio C++ project?  I am able to get the statically linked libs doing the `vcpkg install uwebsockets:x64-windows-static` and I can even build against them.  The problem I am having is that the dll runtimes need to be next to the executable for it to run.  I thought that using static libraries would allow dev to NOT have to ship the dlls.  Any ideas why the `-static` install from vcpkg requires the .dlls

See here for more details:  https://stackoverflow.com/questions/72931905/uwebsockets-static-library-installed-via-vcpkg-but-dll-are-still-needed-for-exec

**Comment by hinell** [comment]
> Look at this https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake

Strictly speaking I think `Find*.cmake` modules are mostly soft-deprecated. It's expected that vendor provides CMakeLists file, not some third-party.

**Comment by eli-schwartz** [comment]
> It's expected that vendor provides CMakeLists file, not some third-party.

Well, I do dearly hope third parties don't provide `CMakeLists.txt`, which is distinct from `Find*.cmake`.

**Comment by hinell** [comment]
@eli-schwartz I mean `CMakeLists.txt` would generate necessary package information modules and install them instead of `FindFoo.cmake`.

**Comment by ZiperRom1** [comment]
Why what it seems to be the best C++ websocket lib is maintained by a smartass cave man who think its 1970 hand written makefile is better than a modern build sytem because "it compiles fine on my environment" :sigh:

**Comment by eli-schwartz** [comment]
I would like to speak in defense of handwritten Makefiles for projects that don't actually make use of any of the functionality which a "modern" build system provides.

However I noticed that the current Makefile now compiles build.c and executes it, and build.c is responsible for executing the compiler via `system()`.

**Comment by ZiperRom1** [comment]
When you need to cross-compile a project from linux to windows with a mingw toolchain with many libs as shared libs, a functionality like `cmake -S . -B build  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DBUILD_SHARED_LIBS=ON` make the things quite simple. Spending time figure it out how to do the same "by hand" is just painful, regarding the number of issues about building shared lib or compiling in windows this project I am not the only one thinking it.

I'm going to setup `vcpkg` in my docker builds env to reuse my CMake toolchain and do the job.

**Comment by uNetworkingAB** [comment]
> Why what it seems to be the best C++ websocket lib is maintained by a smartass cave man who think its 1970 hand written makefile is better than a modern build sytem because "it compiles fine on my environment" :sigh:

Is it good because I'm a cave man, or am I a cave man because it is good?

Clearly it's good because I'm a cave man, because what you are looking for (shared lib compilation) will ruin performance by 80%.

The lib is good, exactly because I don't make it easy to do the wrong thing. You want easy shared lib compilation on windows - both of which lower performance to 10% of where you would be with LTO compiled static lib on Linux.

That's why, the lib is good, exactly because I'm a cave man. Oogha boogha smash

**Comment by eli-schwartz** [comment]
> When you need to cross-compile a project from linux to windows with a mingw toolchain

Literally just setting $CC and $CXX, handwritten Makefiles and all. I've done this for lots of projects with handwritten Makefiles.

> with many libs as shared libs

This is a valid case of

> projects that don't actually make use of any of the functionality which a "modern" build system provides.

And really, cmake will not help you here, because cmake doesn't mean shared libs will be created. The project maintainer doesn't like shared libs? Easily enforced in cmake: just set the library as `STATIC` to disable this cmake feature that won't be used now.

But since it's not being used, there's less motivation to avoid handwritten Makefiles.

> Spending time figure it out how to do the same "by hand" is just painful,

... But this is orthogonal, the complexity of a handwritten Makefile is a developer burden, not an end user burden, it either works or it doesn't. If it works, you don't need to figure out how to use it. If it doesn't work, there's nothing to figure out.

> regarding on the number of issues about building shared lib or compiling in windows this project I am not the only one thinking it.

And that's not really an issue of Makefiles or cmake!

If the project says "no we hate shared libs" then the number of issues about doing that anyway, would exist regardless of build system used. *Any* build system would have issues with shared libs on account of intentionally disabling them. Or simply not caring about them, because you need to specially set up shared libs support on Windows at the `*.cpp` sources level, whereas it works by accident on Linux.

**Comment by ZiperRom1** [comment]
I ended up finding a pull request with a CMake integration in this repo, I just copied his `CMakeLists.txt` rework and tuning it a bit then setup a github action to automatically create release with fetched `uWebsocket` submodule and thats it.

For people who need a CMake integration there is the [fork](https://github.com/ZiperRom1/uWebSockets), I added some options but not all.

Now I can integrate this lib as all others (a dozen or more) in my docker builds env with neat syntax and custom integration.

```dockerfile
FROM alpine:latest

ARG GCC_VERSION
ARG MINGW_VERSION
ARG CMAKE_VERSION
ARG BINUTILS_VERSION
ARG LIBUV_VERSION
ARG U_WEB_SOCKETS_VERSION
# ...

RUN apk add --no-cache bash make gcc=~${GCC_VERSION} g++=~${GCC_VERSION} mingw-w64-gcc=~${MINGW_VERSION} \
    mingw-w64-binutils=~${BINUTILS_VERSION} mingw-w64-headers mingw-w64-winpthreads mingw-w64-crt cmake>${CMAKE_VERSION}

ENV INSTALL_PREFIX=/usr/x86_64-w64-mingw32
ENV CMAKE_TOOLCHAIN=/tmp/mingw-w64-x86_64.cmake
ENV CMAKE_COMMON_OPTION="--install-prefix ${INSTALL_PREFIX} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON"

# Copy cmake toolchain from windows cross compiling
COPY cmake/mingw-w64-x86_64.cmake /tmp

# Install libuv with the given LIBUV_VERSION version from https://github.com/libuv/libuv
RUN wget https://github.com/libuv/libuv/archive/refs/tags/v${LIBUV_VERSION}.tar.gz \
    -q -O /tmp/libuv-${LIBUV_VERSION}.tar.gz && \
    cd /tmp && ls && tar -xvzf libuv-${LIBUV_VERSION}.tar.gz && cd libuv-${LIBUV_VERSION} && \
    cmake -S . -B build ${CMAKE_COMMON_OPTION} -DWITH_OPENSSL=OFF && \
    cmake --build build -j ${MAX_CPU_CORES} && cmake --install build && \
    rm -rf /tmp/libuv-${LIBUV_VERSION}.tar.gz /tmp/libuv-${LIBUV_VERSION}

# Install uWebSockets with the given U_WEB_SOCKETS_VERSION version from forked https://github.com/ZiperRom1/uWebSockets
RUN wget https://github.com/ZiperRom1/uWebSockets/releases/download/v${U_WEB_SOCKETS_VERSION}/uWebSockets-${U_WEB_SOCKETS_VERSION}.tar.gz \
    -q -O /tmp/uWebSockets-${U_WEB_SOCKETS_VERSION}.tar.gz && \
    cd /tmp && ls && tar -xvzf uWebSockets-${U_WEB_SOCKETS_VERSION}.tar.gz && cd uWebSockets-${U_WEB_SOCKETS_VERSION} && \
    cmake -S . -B build ${CMAKE_COMMON_OPTION} -DWITH_OPENSSL=OFF -DWITH_QUIC=OFF -DWITH_BORINGSSL=OFF -DWITH_ASIO=OFF \
    -DWITH_ASAN=OFF -DWITH_LTO=OFF -DWITH_LIBUV=ON -DWITH_ZLIB=ON && \
    cmake --build build -j ${MAX_CPU_CORES} && cmake --install build && \
    rm -rf /tmp/uWebSockets-${U_WEB_SOCKETS_VERSION}.tar.gz /tmp/uWebSockets-${U_WEB_SOCKETS_VERSION}

# ...

WORKDIR /app

CMD ["/bin/bash"]
```

**Comment by uNetworkingAB** [comment]
I tested your CMake variant. The first observation is that, it doesn't work on Linux - it always links to libuv. The second observation is that it builds unoptimized by default, which runs with 30% the performance of a release build. This is major PR suicide to have debug builds by default. But even when specifying release, it still runs significantly slower than when built as is.

So this change, essentially is a performance degradation at best, a performance (and PR) suicide at worst.

**Comment by uNetworkingAB** [comment]
I'm literally getting **300k req/sec with my Makefile** and **268k with your CMake (release)**. This is, the most quintessential example of why I don't let people who have not the slightest idea about what they are doing, weigh in on how this project is to be run. End of story. You don't know what the heck you are doing.

**Comment by uNetworkingAB** [comment]
Btw your fork is breaking the licensing agreement. Will DCMA it in 1 week if not fixed.

**Comment by eli-schwartz** [comment]
> Btw your fork is breaking the licensing agreement. Will DMCA it in 1 week if not fixed.

The CI definition from that fork is GPL2 licenced, which is incompatible with the original project's Apache-2.0 license, but it's not obvious that it constitutes a combined work... it's an odd look to go do that, but I'd still assume that the CMakeLists.txt falls under the project license, not the license that's scoped to the file header for the CI definition.

**Comment by eli-schwartz** [comment]
> If you succeeded cross compiling a lib with "just" setting 2 env vars and no other compile options / directories prefix etc congrats. I hope your hello word printed well on windows.

What an odd skepticism, especially when dealing with a mingw toolchain instead of Visual Studio.

**Comment by uNetworkingAB** [comment]
> > Btw your fork is breaking the licensing agreement. Will DMCA it in 1 week if not fixed.
> 
> The CI definition from that fork is GPL2 licenced, which is incompatible with the original project's Apache-2.0 license, but it's not obvious that it constitutes a combined work... it's an odd look to go do that, but I'd still assume that the CMakeLists.txt falls under the project license, not the license that's scoped to the file header for the CI definition.

This is not what is the problem. I don't care about some CMakeLists.txt file. The person is entirely disregarding the very README.md file like blowing past a stop sign because there seems to be no traffic. This blatant disregard for a) licenses b) benchmarking what you make and c) even making it work on the main platform is what really makes me lose hope in humanity.

**Comment by uNetworkingAB** [comment]
**Intellectual property**, all rights reserved.

**Where such explicit notice** is given, **source code** is licensed Apache License 2.0 which is a permissive OSI-approved license with very few limitations. **Modified "forks" should be of nothing but licensed source code**, and be **made available under another product name.** If you're uncertain about any of this, **please ask before assuming**.

**Comment by ZiperRom1** [comment]
@uNetworkingAB The fork I made is not attended to replace your makefile, it only fit my personal needs (like linking to libuv yes or linking as shared lib), I only shared it as base for people who want a CMake build integration.

> This is major PR suicide to have debug builds by default

Not my problem if people do not set their release type build before building.

> I'm literally getting 300k req/sec with my Makefile and 268k with your CMake (release)

It is just static link with LTO optimisation, for my personnal needs it is perfectly fine to not have a 1 million req/sec as the application is not a server with high demands trafic.

> Btw your fork is breaking the licensing agreement. Will DMCA it in 1 week if not fixed.

Do what you want, if you do not want your project to be used and customized do not put it on an open-source platform which make the later process as easy as a click on "fork this repository" button.

**Comment by uNetworkingAB** [comment]
> I only shared it as base for people who want a CMake build integration

You are, **literally**, legally not allowed to. Not in the current form. This is not opinion, this is basic intellectual property law. Educate yourself in basic law before making legal decisions. None of your opinion matters. This project is owned intellectual property and the more you fight it, the further up your anushole the foot will be for medical removal. Of course, right now it's a non-issue and I don't need to do anything. Should time tell otherwise, we will see.
