### ISSUE TITLE
Missing $DESTDIR in the install statements

### ISSUE THREAD

**Issue by yurivict** [uNetworking/uWebSockets#1057]
https://github.com/uNetworking/uWebSockets/blob/master/Makefile#L37

**Comment by alexhultman** [comment]
You can set prefix to /use/local or /usr

**Comment by yurivict** [comment]
Makefile should contain ```$(DESTDIR)$(PREFIX)```

**Comment by alexhultman** [comment]
Destdir and prefix are virtually identical - do you have a problem using the prefix? I prefer a small minimal Makefile

**Comment by yurivict** [comment]
> Destdir and prefix are virtually identical

No. They are different.
DESTDIR is the stage directory where the project is being temporarily installed, ex. /tmp/my-build-dir/uNetworking
PREFIX is intstallation prefix, ex. /usr/local

**Comment by alexhultman** [comment]
Other than die hard fanatism, do you have any problem achieving your desired goal with the current Makefile?

**Comment by yurivict** [comment]
> Other than die hard fanatism, do you have any problem achieving your desired goal with the current Makefile?

```$(DESTDIR)$(PREFIX)``` is what makes all GNU make projects install properly on all systems when stage directory is used. Stage directories are always used when packages are built. The the problem from my OP breaks packageability.

**Comment by alexhultman** [comment]
Since this is a simple header-only project with a Makefile that literally just cp a folder to a particular directory, you can use prefix to specify exactly where things should go.

I get that more complex projects that want to be GNU-compatible and all that Stallman crap could have DESTDIR but this project really is nothing but one folder of headers - you don't even need a Makefile at all, it's standard C++ files in a folder even for non-Stallman Micro$oft Windows.

The point of the Makefile is basically to have a simple way of building example apps, if I add more GNU features soon we'll have autoconf and all kinds of shit.

Sure, we could add DESTDIR, but I have a real hard time understanding how this really affects your package building - you still need some kind of script calling make, so just put CP in that script and bypass the Makefile entirely. That's why I call this fanatism - because I know for a fact its very possible to do without.

**Comment by alexhultman** [comment]
Alright I added it

**Comment by yurivict** [comment]
Thank you,
