### ISSUE TITLE
Websocket server interrupted suddenly and closeFrame is 1006.

### ISSUE THREAD

**Issue by Shinefallen** [uNetworking/uWebSockets#1068]
The websocket server worked and transformed data correctly for a few minutes but interrupted suddenly. I just got the closeFrame as 1006. The client cannot close this connection( another websocket server tool worked correctly all the time). And now i don't know how to location this problem, so what might result in this? I have tried to change maxPayloadLength and maxBackpressure, and both didn't work.

` auto app = uWS::SSLApp({.key_file_name = "./cert/misc/key.pem",
                            .cert_file_name = "./cert/misc/cert.pem",
                            .passphrase = "1234"});
 app.ws<PerSocketData>("/*", {
	    .compression = uWS::DISABLED,
            .maxPayloadLength = 32 * 1024,
            .idleTimeout = 0,
            .maxBackpressure = 1024 * 1204 * 1204,
            .open = [=](auto *ws, auto *req) {...... },
            .message = [=](auto *ws, std::string_view message, uWS::OpCode opCode) {...... },
            .drain = [](auto *ws) {......}, 
            .ping = [](auto *ws) {}, 
            .pong = [](auto *ws) {},
            .close = [=](auto *ws, int code, std::string_view message) {...... },
	});`

**Comment by alexhultman** [comment]
I work with meritocracy in this project; people who post really good issues are treated better than those who post bad ones. Unfortunately you've posted two issues already with poor quality and I cannot do anything at all with this report since you've cut out you application logic and you don't specify exactly what the issue is.

Therefore I'm not going to bother until you can show strong evidence of an actual issue in the library itself.
