### ISSUE TITLE
Does unix socket are supported

### ISSUE THREAD

**Issue by lmussier** [uNetworking/uWebSockets#1076]
Hi,

It seems none of the listen function is able to take a unix socket.
And don't see if uSocket can use it.

Is there a way to use unix sockets ? Or a plan to support them ?

Thanks.

**Comment by alexhultman** [comment]
No it's not supported. People have asked before but I don't see any reason to support it.

The Linux kernel does localhost TCP faster than any proxy can handle, anyways. And if you need a proxy you better do it over TCP anyways so that you can load balance things.

If you really want a fast connection between proxy and server you should write that as an addon directly in the proxy becuase there is no reason to even have two servers on the same machine to begin with.

So no that is not a thing.
