### ISSUE TITLE
Have an ideal oss-fuzz integration

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#1086]
Currently at 91%, with some new fuzzing strategies this coverage should increase rapidly and it could even make sense to aim for 100% (function) coverage.

What remains is:

* WebSocketContextData.h - free is never called
* WebSocketContext.h - free, on_end, on_timeout is never called
* Loop.h - removePostHandler, removePreHandler, run, integrate, uWS::run is never called
* HttpContext.h - free, on_end, on_timeout is never called

Recently fixed:

* BloomFilter.h - reset was never called (actually a bug)
* Utilities.h - u32toa was never called (removed, not needed)
* ProxyParser - getSourceAddress was never called

I'm guessing the new coverage will be around 95%

**Comment by alexhultman** [comment]
Fuzzing coverage today is 99.5% - only Loop::integrate is never called. Every function except this one is touched by the fuzz targets in some regard.

Region coverage is 88% overall, but this will be improved in tomorrow's stat when fixes have run.

**Comment by alexhultman-2fa** [comment]
Region coverage is at least 93% now

**Comment by alexhultman-2fa** [comment]
Coverage of both uSockets and uWS is 95% now and there are no issues.

But an ideal fuzz integration is much more than coverage - there needs to be a corpus of human readable text files basically being like unit tests. 

This means I will have to think about and put together a bunch of test files according to some format that is easy to understand so that new cases can be easily designed.
