### ISSUE TITLE
GetQuery with optional parameters

### ISSUE THREAD

**Issue by FerLuisxd** [uNetworking/uWebSockets#1091]
Right now the getQuery function will ignore any parameter, woudln't it be nice to have the option to get the exact Query you are looking for?
Making it optional so it doesn't affect performance at all if no params is sent

**Comment by hst-m** [comment]
I ended up moving the API's to websockets because the connection is already open and is faster than http, can use better performing protocols than Query String. JSON.parse is slowest, parsing Query String is faster but other options are faster than those if you use sockets. People still need to parse query strings though so could add getQuery parser and auto-decode is probably helpful

**Comment by alexhultman** [comment]
I have added an implementation for this.

It can do 400 million retrievals and decodes per second, so performance is practically not an issue.

**Comment by alexhultman** [comment]
This is wrapped for Node.js now, try the latest binaries. It is 400x faster than decodeURIComponent.

req.getQuery('keyname')
