### ISSUE TITLE
x-webkit-deflate-frame

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#1157]
Apparently Safari still don't follow the standard regarding compression. Adding an alias för their variant will solve this issue

**Comment by alexhultman** [comment]
x-webkit-deflate-frame is a vendor prefix to deflate-frame which is not the same as permessage-deflate but very close. The only thing that differs is the negotiation of sliding windows.

By supporting this, the exact details of permessage-deflate parameters should be hidden better in a module and only expose the general idea to the rest of the code.

This is one example of how websockets/ws is overcomplicating things by exposing complicated parameters to the end user, while we take the path of having simple-to-use compressors. Things should be simple to understand for end-users and work everywhere.

**Comment by tonso** [comment]
I wonder, did you implement this alias just to enable deflate for Safari, or because there was a report that it wouldn't work properly without this extension acknowledged by the server?

**Comment by alexhultman** [comment]
It's not actually an alias, it has different negotiation rules. But yes Safari still use this and we have to support Safari

**Comment by tonso** [comment]
Yes, I meant that, not alias literally. I'm investigating why Safari sometimes disconnects (with 1006 error) right after receiving the handshake response (without x-webkit-deflate-frame support), that's why I asked if you know anything about the x-webkit-deflate-frame support being mandatory for Safari (though this doesn't comply with the standards), as a possible reason for those disconnects.
