### ISSUE TITLE
How about python support?

### ISSUE THREAD

**Issue by Bloodielie** [uNetworking/uWebSockets#1201]
I saw that you did Python support, but for some reason deleted all the files. Why did you do this, and should we expect python support in the future?

**Comment by Bloodielie** [comment]
saw that you were doing python support but for some reason deleted all files

**Comment by alexhultman** [comment]
I made the python repo private. It is not deleted only hidden. The problem was that nobody seemed to care, and Python has issues with fragmentation such as PyPy being much faster than CPython but lacking C extensions. Also the ASGI thing required extensive performance loss for compatibility since it requires Futures from the asyncio library, which are really, really slow. I will probably not try to get into the Python market since those people are a whole different group and don't seem to know anything about uWS whatsoever. It would be like starting from square 1 and I don't want that.
