### ISSUE TITLE
Group TopicTrees under tenant

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#1206]
* App::publish will publish to all TopicTrees in the App
* WebSocket::publish will publish to its own TopicTree, except for itself

That's strange if you're having multiple websocket contexts. Now you cannot publish to all in a particular websocket context.

It also lacks in ways that you can separate things by static URLs, but not by parameter URLs. Because TopicTrees are tied strictly to the one single websocket context, you can't really implement multi-tenant TopicTrees dynamically.

Solution:

Group all TopicTrees under string tenant and have all functions take string tenant to explicitly state what "namespace" we are talking about. They should not be strictly grouped under websocket context.

**Comment by alexhultman** [comment]
A topic tree has to know what compression to use.

Only a websocket belonging to a WebSocket context with the same compression can subscribe to a topic tree with that compression.

It could be made so that the first websocket to subscribe to a non-existing topic tree sets its compression. Any mismatching subscriptions will simply fail.

So for two websocket contexts to share the same topic tree they would have to use the same compression settings

**Comment by alexhultman** [comment]
This is a good solution in many ways - it fixes the bad APIs and allows for considering a deeper fix in the future where a topic tree could potentially use mixed compression settings. This could be changed in the future without breaking the APIs again.

And for most people who only use one websocket context this really doesn't change anything at all

**Comment by alexhultman-2fa** [comment]
All that **really** has to be done here is to make WebSocket::publish publish to all subscribers but itself **and for all subscribers in all other websocket contexts in this App**.

That change alone will make the **concept** so that 1 App has **conceptually** 1 tree of topics (even though technically there can be many TopicTrees involved).

The important part is nailing the **concept** for v19 - then the implementation of this concept can change in the future.

With this implementation you really can have different compression modes since every websocket context has its own TopicTree.
