### ISSUE TITLE
Configurable HTTP_IDLE_TIMEOUT_S?

### ISSUE THREAD

**Issue by shaylevi2** [uNetworking/uWebSockets#1242]
HTTP_IDLE_TIMEOUT_S is 10 seconds hard coded.

As far as I understood from reading the code, that is the http keep-alive timeout for any non-ws connection (am I wrong?).

Many load balancers have much longer timeouts when communicating with backend services (in many cases, not configurable):

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout
https://cloud.google.com/load-balancing/docs/https#timeouts_and_retries

Is there any way to increase the http keep alive timeout?

**Comment by alexhultman** [comment]
You're correct, but to clarify this is idle timeout - a keep-alive connection can be kept open indefinitely as long as it sees some traffic every 10 second. So your load balancer or proxy could send "pings".

**Comment by shaylevi2** [comment]
I can make a PR to make this configurable if you're interested (ie if there's a chance for it to be merged).

**Comment by alexhultman-2fa** [comment]
The goal is to improve this, yes. This hard-coded timeout is crappy. But I wonder if it makes sense to have this as a dynamic setting when only 1 person has made any comment on it for 6 years. 10 seconds is pretty much fine since the overhead of a connection over LAN-TCP per 10 seconds is the very definition of negligible.

Having this be a compile time setting would probably make the most sense, something like UWS_HTTP_IDLE_TIMEOUT or something like that, as a macro.

**Comment by alexhultman-2fa** [comment]
I mean even if you have 60 seconds timeout for the AWS load balancer, and they recommend a higher than 60 seconds timeout internally, it doesn't really matter since the 10 seconds timeout only matters if your service sees no traffic for 10 seconds. And the only overhead for this, is the establishment of a new TCP connection, over this LAN. That's like 1ms over the period of 10 seconds, and only happens when you have literally 0 traffic.

**Comment by alexhultman-2fa** [comment]
If we make the timeout 120 seconds, 12x as long as 10 seconds, and we say that the establishment of 1 TCP connection takes 1 ms then you save at most 11ms (and this is in the worst possible case) per every passed 120 seconds. That is 0.00009x improvement.

**Comment by alexhultman-2fa** [comment]
I'm fine with this being a macro, with a default value of 10.

**Comment by alexhultman-2fa** [comment]
Are you going to PR this?

**Comment by shaylevi2** [comment]
I see what you're saying about the minimal improvement this would give. 
I guess it's better to leave it out.

(Macro wouldn't be the way I would approach it but rather a config.)
