### ISSUE TITLE
Time to update benchmarks?

### ISSUE THREAD

**Issue by whyCPPgofast** [uNetworking/uWebSockets#1285]
Hi, I trust your benchmarks and would like to see an updated version (of the graphs). There is also a new rust library called tungstenite-rs that is gaining popularity and it would be great if you could include that.

**Comment by alexhultman-2fa** [comment]
No that's not a goal - we mainly compare with Node.js and Deno because those are very popular. Whatever obscure project X does is irrelevant, especially now 6 years later, we already know the margin of improvement to be pointlessly small (less than 1%) so there is no point really. Today I care about QUIC benchmarks
