### ISSUE TITLE
A tiny issue with transitive dependency in PerMessageDeflate.h

### ISSUE THREAD

**Issue by ramblehead** [uNetworking/uWebSockets#1306]
```uint32_t``` type in subj. h-file is used before ```<cstdint>``` include. It makes the h-file dependant on the include order in a translation unit where it used.

The subj. is caught by clangd:
![Screenshot from 2021-08-17 15-48-54](https://user-images.githubusercontent.com/2130398/129763211-940037af-3f7e-4528-a08a-9ee691f1bd17.png)

**Comment by mattfbacon** [comment]
Could you expand the scope of this? Many of the headers don't work properly when including them on their own (for example uWebSockets/HttpResponse.h). Not sure if the author of this repo is aware, but including dependencies inside a header file has no cost if the headers are already included. There is no reason not to, if they are required for the header to work. Additionally, uWebSockets/HttpResponse.h can only be included in one source file due to some function definitions that are not marked inline.

**Comment by mattfbacon** [comment]
Nevermind, I was using an old version of uWebSockets and uSockets. Time to complain to the AUR package maintainer...

**Comment by mattfbacon** [comment]
To clarify, the first part (about include file transitivity) is still an issue. The non-inline functions were fixed.

**Comment by ramblehead** [comment]
@mattfbacon thank your for your response. I was mostly interested to check if the author is interested in fixing such issues as they are not errors as such (might become errors though - depends on a use case). Also, as a secret agenda ;) I wanted to highlight clangd (and other clang-tools) for C++ linting.

I have spent a bit of my time tonight to discover and fix all files with transitive dependency issues that clang-tidy can see:
```sh
run-clang-tidy-11 -checks='-*,misc-definitions-in-headers' 'path/to//uWebSockets/*'
```

Now, as FOSS contributions are terribly complicated these days with licenses, signing something somewhere, various rights movements, language policing and different CI pipelines, I wounder if I should just list my fixes here, create PR or something else?

**Comment by alexhultman** [comment]
It's not complicated to contribute to Apache License 2.0 - it contains basically a CLA already, so all you need to do is accept it and hint of something being a contribution. That's built-in to this license, as compared to many other "anarchy-style" licenses like MIT, ZLIB, etc. Those licenses are messy since they don't cover contributions.

**Comment by mattfbacon** [comment]
@ramblehead, that would be much appreciated! Right now I'm including `<uWebSockets/App.h>` wherever I want to use anything, which I think is increasing compile times by a significant amount.
