### ISSUE TITLE
implement io_uring?

### ISSUE THREAD

**Issue by superdolt** [uNetworking/uWebSockets#1355]
implement io_uring?

**Comment by alexhultman** [comment]
It's not a priority because

a) none of my computers perform better with io_uring (as of Linux 5.13, things are being optimized for 5.16 but still)
b) adopting it would mean complete rewrite of many parts (io_uring is proactor, while epoll is reactor)
c) when QUIC support comes, it will use sendmmsg and recvmmsg which are already capable of sending/receiving many packets per syscall

**Comment by alexhultman** [comment]
I've checked with io_uring since I first heard of it and never seen any improvement on my machines (I have old Intel machines). On ARM64 I can see a small gain now with 5.13, about 13% better in ideal scenarios.

This is on Raspberry PI 4, however this is with mitigations on. Similar can be seen on my old Intel machines, but I'm still pretty sure mitigations off still runs faster with epoll.

If you plan to shove tons of data to from kernel space then obviously io_uring is better since you can map memory and pass it zero copy, but we are not doing that here we only care about small message sending and I still can't see any significant wins that would still be there with mitigations off.

Also it takes time for these new kernels to become mainstream and spread to the audience.

I'm going to see if I can beat my records on this Raspberry PI 4 over LAN, but this all still runs insignificantly better/worse for motivating such a big architectural change (with all the drawbacks associated).

**Comment by markg85** [comment]
> Come back in a year and I can test it again, see where perf. is at. Whenever there is SIGNIFICANT perf. improvement I will certainly bake it into uSockets.

Here's the ping for "a year" later (well.. make that well over 2 years).
I'd be surprised if io uring isn't beneficial at this point. 
If it's not you might need to fiddle with io uring specific knobs in which case i'd suggest to just ping the io uring author, he seems to be responsive and willing to help.

**Comment by uNetworkingAB** [comment]
It is tracked here https://github.com/uNetworking/uWebSockets/issues/1603
