### ISSUE TITLE
Option to allow unmasked frames

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets#1393]
ws frames are masked due to security reasons. However, the masking/unmasking has a performance overhead which we would like to avoid in secured networks.

Can we add an option that allows the server to receive and process unmasked frames?

Refs: https://github.com/websockets/ws/pull/1986

**Comment by alexhultman** [comment]
Uws message parser (including unmasking) can do 50 million messages per second on one shitty core of a 15 year old laptop. This is the definition of premature optimization and is not going to make any difference whatsoever, except breaking the spec.

**Comment by alexhultman** [comment]
I also know we have alignment issues that are simple to fix and would make that 100 million, but this fix never got merged because it literally made no difference to anyone. Nobody is bottlenecked by the parser.

**Comment by alexhultman** [comment]
Generating random bytes in the client is WAY more costly than unmasking, so if you have problems with THEIR client then remove the randomness and just use a fixed mask. That way you remove the whole pseudorandom hashing

**Comment by ronag** [comment]
It’s easy to disable masking on the client. However, yea won’t accept it.

**Comment by e3dio** [comment]
You made a PR https://github.com/websockets/ws/pull/1986 to pool a bunch of randomness for mask, but all you need is generate 1 mask and use it repeatedly, no randomness needed

**Comment by alexhultman** [comment]
> Clients MUST choose a new masking key for each frame, using an
algorithm that **cannot be predicted by end applications** that provide
data. For example, each masking could be drawn from a
cryptographically strong random number generator.

Cryptographically random masks only matters for **web browsers**. This because **web browsers** execute in a sandboxed universe where the **data provider** is separated from the **WS impl.** in the sense that the data provider cannot interfere with the on-wire data.

In the case of Node.js, the data provider and WS impl. are in the same security universe, so cryptographically random masks are **pointless** there and **achieves nothing**.

**Comment by alexhultman** [comment]
I'm closing this. This has nothing whatsoever to do with uws and is a performance problem is websockets/ws.

**Comment by alexhultman** [comment]
The reason web browsers need to mask the data with impossible-to-guess-bytes is because scripts that run as part of a web browser are **untrusted**.

Scripts that run in Node.js are **trusted** and can already do **whatever they want** (including straight up modifying the on-wire data any way it pleases).

Generating a super secure cryptographically random mask when you're **not acting as a web browser** is like playing chess with yourself and being **shocked** that you know what you know and that you cannot trick yourself.

So objectively speaking, the most **sane** decision a non-browser client implementation of the WebSocket protocol can make, is to just have a static mask it reuses or possibly having an uint32_t that increments globally with every message sent. That is spec. compliant and correct in every single way while being much more efficient.

**Comment by e3dio** [comment]
@ronag You could also select a mask of all 0's and send the original data string if you think it will help CPU `{ clearMask: true }`

**Comment by alexhultman** [comment]
Yep. The concept of "cannot guess" goes out the window as soon as you exist in the same very security context. A mask of 0 is really just as secure in this scenario.

**Comment by alexhultman** [comment]
Ugh.. a mask of 0 is probably pushing it too far.

**Comment by e3dio** [comment]
He is using this on his own networks, a mask is only to protect badly written proxy servers which don't properly implement websocket upgrade when attacker controls both server and client. Mask = 0 is best performance and still spec compliant

**Comment by alexhultman** [comment]
Yes but masking with 0 is still asking for trouble. If you mask with any non-zero you're practically guaranteed to never have a problem even with broken proxies. And the cost is not from XOR:ing a few bytes the cost is because they call into OpenSSL for über crypto when its totally unnecessary.

**Comment by alexhultman** [comment]
Skipping unmasking for 100mb messages is only 10% cheaper, so not really anything huge but I have made the change.

**Comment by e3dio** [comment]
Wow 10% is actually pretty big, definitely worth updating your websocket client if it fits your situation, which is probably 90% of the time for non-browsers

**Comment by alexhultman** [comment]
Well yes for 100MB messages that come from non-browsers (aka. very unlikely in real-world usages). The typical message is small and comes from a web browser, so this is really optimizing for a case that is never going to be the average use case.
