### ISSUE TITLE
please please CMAKE?

### ISSUE THREAD

**Issue by alexgu754** [uNetworking/uWebSockets#1474]
can you please please please add CMake? 

it makes everything so much infinitely easier when you can just add_subdirectory() a cmake project and don't have to mess around with building it and linking against it

**Comment by uNetworkingAB** [comment]
No. For about 17 different reasons.

We already have 1 build system and that's 1 too many for a header-only project.

I don't intend to spend one microsecond of time on pointless flame war fanatical bullshit problematics such as "pick my build system because I use it". I use Make, and that's that.

**Comment by alexgu754** [comment]
> No. For about 17 different reasons.
> 
> We already have 1 build system and that's 1 too many for a header-only project.
> 
> I don't intend to spend one microsecond of time on pointless flame war fanatical bullshit problematics such as "pick my build system because I use it". I use Make, and that's that.

it's not a big deal, there is no flame war. it would mean a lot if you were to approve the adding of it.  Clion only works with CMake. it feels so nice when you add it to an existing cmake project and it _just werks_

**Comment by uNetworkingAB** [comment]
I've run this project for 7 years and 98% of all PRs has been "add my build system X" where X is any of the 34 different competing build systems. I have seen it all and I will never spend so much as one second on **other people's inability to adapt to a given reality**.

It's not even up for discussion, it will never happen.

**Comment by alexgu754** [comment]
> I've run this project for 7 years and 98% of all PRs has been "add my build system X" where X is any of the 34 different competing build systems. I have seen it all and I will never spend so much as one second on **other people's inability to adapt to a given reality**.
> 
> It's not even up for discussion, it will never happen.

why don't you just approve them and not give a second through to it?
i realise this repo is free as in freedom. but this is an incredibly close minded apple tier perspective

**Comment by uNetworkingAB** [comment]
> close minded apple tier perspective

That's actually a pretty good analysis.

**Comment by alexgu754** [comment]
> > close minded apple tier perspective
> 
> That's actually a pretty good analysis.

why do you want to be like that and needlessly inconvenience thousands of people? 
is it ok if I fork this repo to add CMake support? I know you have some policy on changing the naming, the name of the fork would just be uWebSockets.CMake

**Comment by uNetworkingAB** [comment]
Out of pure fascination, on a psychological level, can you please put a dot on this map to mark your ideology. I really want to know and after you've done so I can put my dot and we will see why we think so differently.

![image](https://user-images.githubusercontent.com/110806833/187119653-9eab8fa5-6611-4f23-9f95-a59e122620eb.png)

**Comment by alexgu754** [comment]
![lolbert](https://user-images.githubusercontent.com/52216194/187120139-7fc466fb-c5ca-41f7-9927-513ec6150f2c.png)
sure. obviously I fall in the lolbert category. now do you.
not to presume but authoritarian?

**Comment by uNetworkingAB** [comment]
![187119653-9eab8fa5-6611-4f23-9f95-a59e122620eb](https://user-images.githubusercontent.com/110806833/187120366-4d80a5a1-633b-455c-a2d8-6f97ef555496.png)

Interesting...

**Comment by alexgu754** [comment]
> ![187119653-9eab8fa5-6611-4f23-9f95-a59e122620eb](https://user-images.githubusercontent.com/110806833/187120366-4d80a5a1-633b-455c-a2d8-6f97ef555496.png)
> 
> Interesting...

hmm.. ok. so you wouldn't be against it if i create a repo that's called uWebSockets.CMake that's this but with CMake?

**Comment by uNetworkingAB** [comment]
Okay here is some history - 

1. I used to allow people to submit their build systems a few years back, assuming I would not need to do anything. This quickly became a total meltdown where people just dumped scripts and shit and eventually I had to step in and go read a bunch of docs for various build systems to try and get things to work the intended way (some people had messed up optimization and the like, giving seriously wrong impression). Then we had a bunch of PRs that modified the existing CMake like one person wanted it and then some other CMake dude wanted to modify it another way and it just became such a big, unnecessary time waste where people spent weeks tweaking a meta project, rather than care about the project itself.
2. When I removed the build systems and started using make (which is present by default on all Unix systems) things became SO MUCH calmer and the PRs that came were actual code improvements. Everything was perfect.
3. I keep getting posts like you wrote, every now and then with the same idea: "just add it for me, it won't take your time". But since I've been through point 1. I don't want to touch that shit ever again. So much time wasted on pointless shit, and the more you do for others, the less they are prepared to adopt to the situation and spend those 5 minutes doing the shit they need for themselves without dragging me into their projects.

One good video that REALLY shows my view is this one: https://www.youtube.com/watch?v=CvagWNaGf58

I don't care what you do as long as you don't market it as if it was my verbatim work.

**Comment by uNetworkingAB** [comment]
I also remember having to fix the CMake files for people being on **older** CMake versions, so I had to backport stuff, and whenever new files or options were added I had to add those in all build systems. And new options I needed were not supported in older CMake versions and I even stumbled on a few breaking bugs in CMake itself that had to be waited for to be fixed. I had to test things on Windows, because CMake is fantastically broken there. Basically, I've spent **ridiculous** amount of time just increasingly falling into this pit of black tar where people will just step on you, assuming I will just agree to any little variation of their requirement. It goes from being "oh but this thing will help thousands", to me just spending 20+ hours of work per day for zero pay.

In fact the single most important lesson I've learnt these 7 years has been to say no. Just say no, and demand pay. That way of thinking has changed my life to the better by about a factor of 10000x, not kidding.

Therefore, even as we had fun times looking at charts, the answer is a big fat no.

**Comment by alexgu754** [comment]
hmmm.. ok I didn't appreciate how hard it was to properly implement cmake for this case. almost every library I've used had CMake except bgfx where the guy just didn't feel like it and wanted to invent his own build system, that's what I thought was happening here too.

I just needed to make a crappy webserver to release a webgl demo of my game to get people to buy the real thing. CMake makes this 'easy'. I didn't want to use nodejs because I feel C++ is superior due to strong typing & more advanced features, so I just googled some projects and this one that had lots of stars.

**Comment by uNetworkingAB** [comment]
> release a webgl demo of **my game** to get people to **buy** the real thing. CMake **makes this 'easy'**.

This is why I thought you were a communist. Because you seem to want free stuff from others, and expect others to help you achieve your goals for your gain. Why would anyone help you for free? It boggles my mind how anyone can think that way. Why would I raise a finger for your monetary gain, when I get nothing? If you started the message like "hey I'm building this game and I want CMake can you ship it for 500 usd" it would be a completely different story.
