### ISSUE TITLE
HttpServer.cpp example returns error when attempting to connect

### ISSUE THREAD

**Issue by jakubcieslak22** [uNetworking/uWebSockets#1477]
The error I'm getting upon trying to reach the server with my browser is:
```
Did not find file: /
Error: Returning from a request handler without responding or attaching an abort handler is forbidden!
```
Now I know that there has been an issue regarding the same error in the past, however the answer is mostly vague and does not fix the problem. I know that the JavaScript example is working just fine, however I would like this C++ version to work properly as well. How could I make it work?

**Comment by uNetworkingAB** [comment]
Looks like the file not being found makes the server not respond

**Comment by jakubcieslak22** [comment]
What file? At no point have I specified "/" as any kind of path. The root directory of the server is a folder inside of my solution's main directory.

**Comment by uNetworkingAB** [comment]
Looks like that example is broken. I haven't looked at it in a long while.

**Comment by jakubcieslak22** [comment]
I'd be grateful if you managed to have a look at it, thank you.

**Comment by e3dio** [comment]
@jakubcieslak22 It is very simple, the example just needs to return a 404 response instead of only logging to console https://github.com/uNetworking/uWebSockets/blob/master/examples/helpers/AsyncFileStreamer.h#L31

It is exactly as the error says "Returning from a request handler without responding or attaching an abort handler is forbidden!" nothing complicated about it. If you spent 1 second reading the example file you are running, you would see it sets up wildcard route here https://github.com/uNetworking/uWebSockets/blob/master/examples/HttpServer.cpp#L69 then when file is not found, it needs to respond with 404. You should open PR to fix issue, takes 1 line of code

**Comment by uNetworkingAB** [comment]
This example hasn't been updated or finished, ever. So consider it a broken example that's not supposed to work.
