### ISSUE TITLE
How shoud we report security issues?

### ISSUE THREAD

**Issue by Catminusminus** [uNetworking/uWebSockets#1497]
I found some behaviors that seem vulnerabilities in uWebSockets. 
However, there is no guide for reporting security issues here.
​
Where can I report the vulnerabilities?

**Comment by uNetworkingAB** [comment]
You can send me a mail

**Comment by Catminusminus** [comment]
@uNetworkingAB 

Thank you for your response.
Which one is better for you, sending one report including all vulnerabilities or sending one report for each vulnerability?

**Comment by uNetworkingAB** [comment]
I have Gmail they will end up pretty much the same either way; a thread. So it makes no difference

**Comment by uNetworkingAB** [comment]
You haven't sent me anything yet but I can already guess where this is going.

Preemptively I can already say that uWS doesn't, and will probably never, implement all weird edge-cases of http1.1.

This is not a vulnerability. It just means uWS will not have 100% spec compliant behavior in all weird edge-cases of http1.1.

The important here is that uWS works for 99% of real world apps and never leaks encrypted data, never crashes, never goes out of bounds or in any way breaks down or leaks data.

What I'm guessing you will make a big deal of is that two different http servers can make two different interpretations of edge case http 1.1, depending on how strictly they implement these messy http1.1 edge cases.

This is again not a vulnerability. If you build an app that blindly relies on two differently manufactured http servers making the identical interpretation of edge case http data, then you're a menace and you're building the most fragile app the world has seen. You're going out of your way to build something broken.

Either you let a proxy interpret the edge cases, sending non-edge case http down, or you put two http servers of the same brand in use if you really require such a fragile behavior. It's pretty obvious that if you send edge-case borderline broken http through one brand of server and expect another brand of server to make the identical exact interpretation in every case possible then you're wishing for failure.

The same idea can be applied to literally any protocol implemented by different vendors. You can have JSON parsers that differ in edge cases producing the same exact problem. You can have Microsoft Word documents produce different interpretations in two different implementations.

This is a natural outcome of having different implementations.

**Comment by uNetworkingAB** [comment]
Here is a counter example:

1. Http1.1 does not define a strict limit on maximum header size. But there obviously needs to be one (call it implementation detail A).

Now, a proxy that limits headers to 16kb and just "ignores and passes the data through" (or whatever it wants to do) when that limit is reached - will very obviously make a different interpretation of the data than a server that picked a limit of 64kb. Now we have caused a "security vulnerability" since the first server ignored some important header and passed the message through and now you have deviated behavior.

Spooooooooky! We just broke the security!

There are tons of these undefined cases in http1.1 where you will have differing behavior so relying on a specific exact behavior is like shooting you in the foot an expecting to win a marathon the next day. It's self inflicted damage.

**Comment by uNetworkingAB** [comment]
I still haven't received any of these supposed vulnerabilities. Please send so I can have a look

**Comment by uNetworkingAB** [comment]
I don't think there are any issues, been looking at RFC 9112 a bit here and even if we do things sloppily at places none of this should be an issue. If you are referring to (guessing from your github activity) "request smuggling" these are not possible since it is invalid for a proxy to send us both content-length and transfer-encoding, and if the proxy sends us transfer-encoding then it is valid for us to assume the proxy did chunked encoding and either accept it or not. All cases are valid for us according to 9112.

While looking at this spec I've done some changes to uWS to be more spec. compliant (still some changes to do) but I really cannot think of any vulnerability here.

Please send what you have, I still have not received anything. I want to close this as quickly as possible.

**Comment by uNetworkingAB** [comment]
Alright I'm closing this as you have not responded or sent me anything.

I've found one class of issue namely the 11.2 part of RFC 9112 which is only an issue if you are using a proxy and you rely on the proxy being able to filter certain URLs. These are fixed in two steps:

1. More strict use of transfer-encoding and content-length
2. Making reading of content-length more strict in terms of overflows, same for chunk lengths in chunked encoding.

These are not really "vulnerabilities" when looking at uWS itself, they are more vulnerabilities in a _deployment_ of a proxy and uWS with filter rules not implemented in uWS but in the proxy.

My opinion is that, doing such a set up is begging for issues since it requires all parts being entirely spec. compliant here and the smallest deviation will break the filtering mechanism. I would say if you care about your data, then apply filtering where you have you data or partition your network so that sensitive data is not even reachable from the front-end proxy at all.

I would file these issues more under "spec. compliance" and I will implement all changes needed to make it so.

Kind of like talking to a brick wall here but I guess, thanks for the input. It made me look deeper at this.

**Comment by Catminusminus** [comment]
@uNetworkingAB 
Sorry for not getting back to you sooner.
I sent an email describing my findings..

**Comment by uNetworkingAB** [comment]
Thanks. Yeah like I wrote these are all 11.2 compliance issues:

> We found three HTTP Request Smuggling (HRS) Vulnerabilities in
`uWebSockets`.

These aren't vulnerabilities in uWS itself, they apply to set-ups that have proxies that expect to be able to block requests based on url.

These http1.1 spec compliance issues will gradually be fixed as we become more spec compliant with RFC9112.

A recommendation is to not put all your eggs in one basket protected by an inherently fragile blocking mechanism that has been broken in pretty much every http server ever created. Instead use proper network partitions to separate interval traffic from external.

Honestly it boggles my mind how anyone could even think of relying on such a broken feature when you have sensitive data exposed under a separate http route - this way of thinking is new to me, I would never ever rely on two parsers from two different vendors to always parse a text format with 4534 different versions, the identical way.

Honestly, I still wouldn't trust such a feature even if servers claim to be "protected" from it since it just takes ANY differing behavior to completely break that feature.

I would instead just make it so that proxies aren't allowed to block certain URLs since doing so is such a fundamentally broken feature.

**Comment by uNetworkingAB** [comment]
I appreciate the detailed reports but the more I look at them the less important they seem:

All three issues are of the form "use uWS as the proxy that forwards to a backend server that does X instead of Y". uWS **isn't even a proxy** and has no such functionality.

One of the three reported issues is that we don't break when host header is missing, how on earth can that be a "vulnerability".

I'm thankful for the nice work made and I have easy fixes that will be made but this is really stretching the wordage "vulnerability" to its breaking point.

One issue is that we trim whitespace between header key and the colon, instead of rejecting the request. This simply **is not** a vulnerability. The header is reported to the app trimmed and there is no such functionality that allows forwarding the original untrimmed key, because again uWS is not a proxy and it has no such functionality.

The final issue is that we don't break when a header value contains LF or NULL. This is again an issue on the basis that if uWS was a proxy that forwarded the raw request then some shittily implemented downstream server could interpret that LF as CRLF....

Anyways, will apply these fixes but they are really nit picking spec compliance issues not vulnerabilities.
