### ISSUE TITLE
What would it take to implement a client?

### ISSUE THREAD

**Issue by aboeglin** [uNetworking/uWebSockets#1710]
Hello!

I'd be willing to give a go at implementing the ClientApp.
Would you happen to have anything in mind or some pointers that may help get started?

Thanks!

**Comment by uNetworkingAB** [comment]
There is no client because nobody is ready to pay for a client to exist. And therefore no client should exist. There is no incentive for me to take on the task of vetting your work, supporting it and adding the eventual heap of extra features people will require. In fact, there is a strong incentive for me to actively postpone a client as it remains a payable project.

**Comment by markmaker** [comment]
How much are we talking?

How much if it includes a simple reverse proxy (http+ws) example?

What time frame are we talking?
