### ISSUE TITLE
Creating new groups on Nodejs

### ISSUE THREAD

**Issue by vaxosoft** [uNetworking/uWebSockets#693]
I want to create new uws groups on Nodejs to use them as rooms for broadcast purposes. I was looking for the source code for Nodejs binding to find out if custom groups are supported, but could not find it. I know they are supported in C++ by creating new groups and adding websockets to it. Nodejs uws documentation covers only simple cases.

So, is it possible to create new groups in Nodejs? If yes, how? If no, is source code for Nodejs binding available online, so that I can consider adding that feature to it? I have implemented rooms in Nodejs, but it is not as efficient, as it is not taking advantage of native prepared messages.

**Comment by alexhultman** [comment]
Groups are not the same as rooms (as in pubsub). Groups are essentially a palette of callbacks which are shared between all sockets in the group. It's a way to specify a shared behavior without attaching the same callbacks over and over again to every socket.

This does not apply to Node.js since nobody wants it there. You can prepare messages for broadcast without groups, even in Node.js.

**Comment by vaxosoft** [comment]
I have implemented a stripped down version of socketio api on top of uws and I am happy with the results. I guess prepared messages is all I need. How can I prepare messages from Nodejs? Is it uws specific or Nodejs specific? Can you point me to the right direction?

Big thanks.

**Comment by alexhultman** [comment]
Where did you learn about prepared messages and why did you not find how to use them from that source? I don't remember how they look like but uws.js contains them, you just have to open the file and look for them. There are also many other issues about this, you just have to search.
