### ISSUE TITLE
Add pub/sub fundamentals

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#790]

**Comment by alexhultman** [comment]
They are added, WIP

**Comment by robnobber** [comment]
Hi, any news on this?

**Comment by ThomasTram** [comment]
Hi

In my application I need to publish messages from another thread. I don't know if this functionality will be added in the future, and what I did feels like a hack. However, I wanted to share it anyway, in case it could be useful to anyone. (And if there is a better way to do this, please let me know!)

I added the following function to WebSocketContext.h:
````
void ServerPublish(const std::string& topic, const std::string& message) {
        uWS::WebSocketContextData<false> * wsData = getExt();
        char dst[1024];
        assert(message.size() < 1024);
        size_t dst_length = uWS::protocol::formatMessage<true>(dst, message.data(), message.length(), uWS::OpCode::TEXT, message.length(), false);
        wsData->topicTree.publish(topic, dst, dst_length);
    }
````
And I added an additional .run() method to App.h that can return a pointer to the WebSocketContexts vector. Of course, this is super dangerous, since it becomes undefined when the App goes out of scope, so we need to be careful.
````
TemplatedApp &&run(std::vector<uWS::WebSocketContext<SSL, true> *>** webSocketContextsPtr) {
        *webSocketContextsPtr = &webSocketContexts;
        uWS::run();
        return std::move(*this);
    }
````
