### ISSUE TITLE
How to stop the uWS::TemplatedApp<T>::run()?

### ISSUE THREAD

**Issue by daxiazh** [uNetworking/uWebSockets#809]
Leave the run()'s loop and clear WebSocket's server!
uWS::TemplatedApp<T>::run() is run in a thread.

**Comment by alexhultman** [comment]
You cannot. It runs until it is done. If you want it to stop you have to let it return. You do that by closing all "async" things such as sockets, timers, etc.

When you app.listen you get a "token". That's actually just a us_listen_socket pointer that you can us_listen_socket_close() with according to docs of µSockets. Then it will fall through and return.

**Comment by alexcohn** [comment]
It's true, us_listen_socket_close() does eventually shut the loop down. But this takes a long while. Here is a [minimal test](https://gist.github.com/alexcohn/c7f1d215fd2f1f904dc864e1ba881f2f): I save the **listenSocket** in `.listen()` and call `us_listen_socket_close()` when the Url starts with `'q'`. 

This simple code does terminate the loop, and seems to do so cleanly. But it takes some **8 sec** to exit the loop. On 0.14 I could simply set `hub.getLoop()->numPolls = 0`, and it took less than **0.8sec** to exit `hub.run()`.

The question is, why there is no mechanism to shut down faster?

**Comment by alexcohn** [comment]
OK, [figured it out](https://gist.github.com/alexcohn/c7f1d215fd2f1f904dc864e1ba881f2f#file-shutdown-0-17-4-kqueue-fast-cpp), at least for the 'default' epoll_kqueue: _**instead**_ of `us_listen_socket_close()`, I set `us_loop_t::num_polls` to 0, and wakeup the loop.

There are two caveats to this approach: for one, a different approach is necessary for **libuv** (and I don't care about **gcd** for now). Second, since `numPolls` member is not declared **volatile**, there is no guarantee that the loop thread will see the change.

But this bug applies to the current ways of working with pools, e.g. `us_create_poll()`. I don't know what other fields follow the same pattern of being used on one thread, while changed on another.

**Comment by alexhultman-2fa** [comment]
@alexcohn Both of your approaches are extremely broken and hacky. You should really read the user manual carefully before trying to forcefully bend things your way. I already posted the answer to this closed issue above.

**Comment by alexcohn** [comment]
I have carefully read [your answer](https://github.com/uNetworking/uWebSockets/issues/809#issuecomment-455098873), and that's why I am posting these questions here. I sincerely want to understand what is wrong with my approach (except relying for 0.17.4 on _private_ API), and how the loop can be closed quickly and cleanly.

**Comment by alexhultman-2fa** [comment]
You are doing all kinds of invalid threading, you have to read the user manual. What you propose in those Gists is fundamentally wrong. I can't personally tutor you, you have to read the text.
