### ISSUE TITLE
End-users should not have to add shorter routes before longer ones

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#822]
We could simply store all routes in a vector of pairs, then at some final moment sort them by length (number of segments) and build the route tree with shorter routes added before longer ones.

This would solve many matching surprises.

**Comment by alexhultman-2fa** [comment]
Stable sort them by length to keep order of same length

**Comment by alexhultman-2fa** [comment]
The order of matches is basically impossible to reason about. The issue here is that Express match in order of registration, in a linear list of routes (algorithmically stupid but easy to reason about), while uWS match with a tree (algorithmically smart but hard or impossible to reason about / control match order).

So the rules need to change - we need to establish that adding routes in one order will be exactly the same as adding them in another order.

So to make matching somewhat sane we need to sort them like so:

Static routes always match first
Paremeter routes match second
Wildcard routes match last

I think this is the only solution when having a tree

**Comment by alexhultman** [comment]
Please have a test with npm install uNetworking/uWebSockets.js#binaries
