### ISSUE TITLE
Improved http timeout logic

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets#838]
keepAliveTimeout should be low 10 seconds
streamTineout should be high 300 seconds

They should be settable in App constructor

onData streaming should have timeout and should always end with isLast immediately if there is no data

**Comment by alexhultman** [comment]
It can also be measured in lowest allowed throughput like kbps limit

**Comment by RDP1974** [comment]
Hello,
Can I ask how much scale uwebsockets c++? How many concurrent websockets can be managed into a single server with or without ssl?
There is a guy having loaded one million of websockets using other nodejs libev based lib.
Thank you

Roberto Della Pasqua
www.dellapasqua.com

**Comment by alexhultman** [comment]
@RDP1974 How long is a rope? "a single server" can mean literally anything. This is not the place to discuss that, though

**Comment by alexhultman** [comment]
If these are passed in App constructor they will surely require an API break so v19

**Comment by alexhultman** [comment]
It is not really about whether these are configurable or not, it is about the current logic being sometimes problematic. There is a fix timeout of 10 seconds for every **chunk** which works in most cases but can be very problematic if chunks written to kernel are HUGE. Timeout should scale with number of bytes written to kernel, to keep timeouts sane in all cases.

**Comment by uNetworkingAB** [comment]
On the writing side the problem is in favor of the server (slow receiving clients will get disconnected) because the kernel only emits writable events in large chunks.

On the reading side (posting a file to the server), the problem is in favor of the client - the client can send 1 single byte every 10 seconds and keep the connection open for as long as it wants. This can be a problem and here there needs to be a minimum number of bytes per 10 seconds that needs to be received.

I'm setting a default of 16kb/sec as lowest allowed receive throughput for now.
