### ISSUE TITLE
HTTP/2?

### ISSUE THREAD

**Issue by mattbishop** [uNetworking/uWebSockets#866]
Any interest in supporting HTTP/2?

**Comment by alexhultman** [comment]
Same answer as for #865

**Comment by Tronix117** [comment]
Is it still not a priority ? Some interesting stuff are coming along HTTP2, like gRPC

**Comment by alexhultman-2fa** [comment]
It might be a priority in 3 years or something, if I'm still actively working on it by then. What I am interested in is primarily websockets, not http. My priorities are in slimming down the low level parts, not in following trends just because.

I actually realised I've cared way too much about http and these pointless req/sec battles, and started to go back to my initial goals; super cheap/lightweight websockets.
