### ISSUE TITLE
GCC build

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets#872]
Apparently it doesn't seem to build with GCC due to protected members in AsyncSocket..

**Comment by lshamis** [comment]
I think I'm getting the same issue:
```
In file included from external/uWebSockets/src/HttpContext.h:26:0,
                 from external/uWebSockets/src/App.h:24,
                 from test/code.cc:60:
external/uWebSockets/src/AsyncSocket.h: In member function 'std::string_view uWS::AsyncSocket<SSL>::getRemoteAddress()':
external/uWebSockets/src/AsyncSocket.h:94:9: error: there are no arguments to 'us_new_socket_remote_address' that depend on a template parameter, so a declaration of 'us_new_socket_remote_address' must be available [-fpermissive]
         us_new_socket_remote_address(SSL, (us_new_socket_t *) this, buf, &ipLength);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/uWebSockets/src/AsyncSocket.h:94:9: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
```

**Comment by alexhultman** [comment]
It now builds, but needs better fix

**Comment by dvergeylen** [comment]
Against which `gcc` version did you test?

with `gcc` 8.3.0 it fails to compile the examples. Reproducible setup:

```bash
cd /tmp
git clone --recurse-submodules https://github.com/uNetworking/uWebSockets
cd uWebSockets
make # → works out of the box with clang 👍

sed -i s/clang++/g++/g Makefile
sed -i s/clang/gcc/g Makefile
make
``` 

outputs:

```bash
gcc -DLIBUS_NO_SSL -flto -O3 -c -IuSockets/src uSockets/src/*.c uSockets/src/eventing/*.c
g++ -DLIBUS_NO_SSL -DUWS_NO_ZLIB -flto -O3 -c -std=c++17 -Isrc -IuSockets/src examples/HelloWorld.cpp
g++ -flto -O3 -s *.o -o HelloWorld
rm *.o
gcc -DLIBUS_NO_SSL -flto -O3 -c -IuSockets/src uSockets/src/*.c uSockets/src/eventing/*.c
g++ -DLIBUS_NO_SSL -DUWS_NO_ZLIB -flto -O3 -c -std=c++17 -Isrc -IuSockets/src examples/HelloWorldThreaded.cpp
g++ -lpthread -flto -O3 -s *.o -o HelloWorldThreaded
rm *.o
gcc -DLIBUS_NO_SSL -flto -O3 -c -IuSockets/src uSockets/src/*.c uSockets/src/eventing/*.c
g++ -DLIBUS_NO_SSL -DUWS_NO_ZLIB -flto -O3 -c -std=c++2a -Isrc -IuSockets/src examples/EchoServer.cpp
examples/EchoServer.cpp: In function ‘int main()’:
examples/EchoServer.cpp:33:6: error: no matching function for call to ‘uWS::TemplatedApp<false>::ws<main()::PerSocketData>(const char [3], <brace-enclosed initializer list>)’
     }).listen(9001, [](auto *token) {
      ^
In file included from examples/EchoServer.cpp:1:
src/App.h:102:20: note: candidate: ‘template<class UserData> uWS::TemplatedApp<SSL>&& uWS::TemplatedApp<SSL>::ws(std::__cxx11::string, uWS::TemplatedApp<SSL>::WebSocketBehavior&&) [with UserData = UserData; bool SSL = false]’
     TemplatedApp &&ws(std::string pattern, WebSocketBehavior &&behavior) {
                    ^~
src/App.h:102:20: note:   template argument deduction/substitution failed:
examples/EchoServer.cpp:33:6: note:   cannot convert ‘{SHARED_COMPRESSOR, (16 * 1024), <lambda closure object>main()::<lambda(auto:14*, auto:15*)>{}, <lambda closure object>main()::<lambda(auto:16*, std::string_view, uWS::OpCode)>{}, <lambda closure object>main()::<lambda(auto:17*)>{}, <lambda closure object>main()::<lambda(auto:18*)>{}, <lambda closure object>main()::<lambda(auto:19*)>{}, <lambda closure object>main()::<lambda(auto:20*, int, std::string_view)>{}}’ (type ‘<brace-enclosed initializer list>’) to type ‘uWS::TemplatedApp<false>::WebSocketBehavior&&’
     }).listen(9001, [](auto *token) {
      ^
make: *** [Makefile:13: examples] Error 1
```

Did I miss something?

Tested with 93b6971bf75e6360cfdc659d3a5ef5ea95b8e305
```bash
gcc --version
# gcc (Debian 8.3.0-6) 8.3.0
```

**Comment by dvergeylen** [comment]
Could find the problem: `g++` fails to make template argument deduction/substitution because of missing `.idleTimeout` argument in the `struct WebSocketBehavior` initialization.

Adding the missing parameter makes `examples/EchoServer.cpp` and `examples/EchoServerThreaded.cpp` compiling fine.

Would you mind a PR (1 line in each of the two examples)?

**Comment by JadeVand** [comment]
I'm having the same issues unfortunately because Apple's Clang at the moment lacks C++17 support until the next Xcode revision (11.0) current is 10.3 with C++14 support. So until then I can just use your v0.14 branch.

**Comment by alexhultman** [comment]
Apple has best C++ support in the industry. You definitely have C++17 support on their platforms. I build on their platforms all the time.

**Comment by louisabraham** [comment]
I get this error on gcc version 8.3.0.


```
g++ -flto -O3 -lpthread -Wconversion -std=c++2a -IuWebSockets/src -IuWebSockets/uSockets/src main.cpp -o server uWebSockets/uSockets/*.o -lz
```

```
main.cpp: In function ‘int main()’:
main.cpp:107:6: error: no matching function for call to ‘uWS::TemplatedApp<false>::ws<main()::PerSocketData>(const char [3], <brace-enclosed initializer list>)’
     }).listen(9000, [](auto *token) {
      ^
In file included from main.cpp:3:
/usr/local/include/uWebSockets/App.h:133:20: note: candidate: ‘template<class UserData> uWS::TemplatedApp<SSL>&& uWS::TemplatedApp<SSL>::ws(std::__cxx11::string, uWS::TemplatedApp<SSL>::WebSocketBehavior&&) [with UserData = UserData; bool SSL = false]’
     TemplatedApp &&ws(std::string pattern, WebSocketBehavior &&behavior) {
                    ^~
/usr/local/include/uWebSockets/App.h:133:20: note:   template argument deduction/substitution failed:
main.cpp:107:6: note:   cannot convert ‘{SHARED_COMPRESSOR, (16 * 1024), 60, ((1 * 1024) * 1024), <lambda closure object>main()::<lambda(auto:11*)>{clients}, <lambda closure object>main()::<lambda(auto:12*, std::string_view, uWS::OpCode)>{clients}, <lambda closure object>main()::<lambda(auto:13*)>{}, <lambda closure object>main()::<lambda(auto:14*)>{}, <lambda closure object>main()::<lambda(auto:15*)>{}, <lambda closure object>main()::<lambda(auto:16*, int, std::string_view)>{clients}}’ (type ‘<brace-enclosed initializer list>’) to type ‘uWS::TemplatedApp<false>::WebSocketBehavior&&’
     }).listen(9000, [](auto *token) {
```

On the other hand, gcc version 10.2.0 works.

**Comment by alexhultman-2fa** [comment]
You don't have to use C++20. You can construct the WebSocketBehavior like any regular struct if your compiler doesn't support designated init. Then you only need C++17

**Comment by louisabraham** [comment]
I actually use C++17 on my main dev machine, this was on my raspberry pi. 

> You can construct the WebSocketBehavior like any regular struct

What do you  mean? It is strange, some of the examples compile (like UpgradeSync and UpgradeAsync), the others give the same error.

**Comment by alexhultman-2fa** [comment]
You're passing a struct. You can init it in old ways that your old compiler understands. You don't need to use "dot init" like the examples do. That requires proper C++20.

**Comment by louisabraham** [comment]
Ah I see. The fix was to add `        .upgrade = [](auto *res, auto *req, auto *context){},` ABOVE open.

**Comment by louisabraham** [comment]
Actually, this leads to the server not being happy with `Error: Returning from a request handler without responding or attaching an abort handler is forbidden!`. The fix is to use the default initialization: `.upgrade = nullptr,`.

**Comment by mark-nick-o** [comment]
with version 10.3.0
i get this and the makefile doesnt seem to let me make uSockets objects with this compiler 

>> g++-10 -flto -O3 -lpthread -Wconversion -std=c++17 -IuWebSockets/src -IuWebSockets/uSockets/src chatbot_orig.cpp -o server uWebSockets/uSockets/*.o -lz
lto1: fatal error: bytecode stream in file ‘uWebSockets/uSockets/bsd.o’ generated with GCC compiler older than 10.0
compilation terminated.
lto-wrapper: fatal error: g++-10 returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status


with 8.40 or 7.5.0 or 4.8.5 i get the same as above
>> g++-8 -flto -O3 -lpthread -Wconversion -std=c++17 -IuWebSockets/src -IuWebSockets/uSockets/src chatbot_orig.cpp -o server uWebSockets/uSockets/*.o -lz
chatbot_orig.cpp: In function ‘int main()’:
chatbot_orig.cpp:73:14: error: no matching function for call to ‘uWS::TemplatedApp<false>::ws<PerSocketData>(const char [3], <brace-enclosed initializer list>)’
             }).listen(9001, [](auto* listen_socket) {
              ^
In file included from chatbot_orig.cpp:3:
/usr/include/uWebSockets/App.h:184:20: note: candidate: ‘template<class UserData> uWS::TemplatedApp<SSL>&& uWS::TemplatedApp<SSL>::ws(std::__cxx11::string, uWS::TemplatedApp<SSL>::WebSocketBehavior<UserData>&&) [with UserData = UserData; bool SSL = false]’
     TemplatedApp &&ws(std::string pattern, WebSocketBehavior<UserData> &&behavior) {
                    ^~
/usr/include/uWebSockets/App.h:184:20: note:   template argument deduction/substitution failed:
chatbot_orig.cpp:73:14: note:   cannot convert ‘{9999, <lambda closure object>main()::<lambda(auto:11*)>{latest_id}, <lambda closure object>main()::<lambda(auto:12*, std::string_view, uWS::OpCode)>{}, <lambda closure object>main()::<lambda(auto:13*, int, std::string_view)>{}}’ (type ‘<brace-enclosed initializer list>’) to type ‘uWS::TemplatedApp<false>::WebSocketBehavior<PerSocketData>&&’
             }).listen(9001, [](auto* listen_socket) {

>> g++-7 -flto -O3 -lpthread -Wconversion -std=c++17 -IuWebSockets/src -IuWebSockets/uSockets/src webserver.cpp -o server uWebSockets/uSockets/*.o -lz
lto1: fatal error: bytecode stream in file ‘uWebSockets/uSockets/bsd.o’ generated with LTO version 2.2 instead of the expected 6.2
compilation terminated.
lto-wrapper: fatal error: g++-7 returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status

**Comment by wangyongxiao** [comment]
> Ah I see. The fix was to add ` .upgrade = [](auto *res, auto *req, auto *context){},` ABOVE open. Thanks!

yes，Thanks，I add

        .closeOnBackpressureLimit = false,
        .resetIdleTimeoutOnSend = true,

then is work！

**Comment by alexhultman** [comment]
Yes unfortunately order matters in C++, but not in C
