### ISSUE TITLE
PerSocketData initialization

### ISSUE THREAD

**Issue by gmatej** [uNetworking/uWebSockets#896]
As PerSocketData is not really initialized, only memory allocated. C++ classes like std::string cannot be used inside this structs. Is there a wait to initialize this structs?

Reading documentation it's discouraged to use a map for tracking sockets. But to use PerSocketData, but how to access PerSocketData from outside for full-duplex comm? Does anyone know a good pattern?

**Comment by alexhultman** [comment]
You can use placement new

**Comment by ddevienne** [comment]
But who will call the destructor when needed?
W/o allowing to register a custom Deleter, as an std::function or similar,
there's no way to properly cleanup that resource. Or am I missing something?

**Comment by alexhultman** [comment]
You call the destructor in close event

**Comment by ddevienne** [comment]
I see. Thanks. I tend to prefer registering a resource-release functor with the framework, right next to the code doing the resource-acquisition myself, rather than having to do the resource-release elsewhere, but that does force you to store that std::function or equivalent yourself in the framework. Fair enough.

**Comment by alexhultman** [comment]
Yeah this is not super nice as is. The library should probably take care of this automatically but I haven't thought more about it

**Comment by ddevienne** [comment]
I only see two design alternatives myself about this:

Raw chunk of memory, and ability to register custom deleter functor stored by the framework, called when connection goes away automatically.

Connection instead of memory chunk allows to store a boost::any, which is by-value so cleans up naturally. Or in the same vein, stores a std::shared_ptr<void> thus forcing clients to heap-alloc their custom per-connection data.

Both any and sptr heap-alloc. But a custom deleter also typically heap-allocs too (std::function does AFAIK). So in all cases, there's an heap-alloc when using per-connection custom data IMHO.

The only advantage of your current approach of a memory-chunk as placement-new into, to be released explicitly in close() is that there's no heap-alloc involved. But than memory-alignment issues are there responsability of the client code, which using any or sptr avoids this complexity.

My $0.02 :). --DD

**Comment by alexhultman** [comment]
App.ws is a template function taking per socket data type so all you really need is to add two lines code to that template; placement new and explicit destructor call. Then your power socket data structure gets init and free automatically

**Comment by alexhultman** [comment]
The problem is one app can have many different .ws routes. So constructing the type is no problem, but then the websocket context cannot know what type to destruct since there can be many routes. So you still have to construct the type yourself using placement new.

Or you can just have type void ptr and use whatever
