### ISSUE TITLE
Streaming to pipelining client

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets#974]
Hi.
Thanks for library.

I got issue in my library issues, which describes this:
- When testing with `stream file`, under high-load headers duplicated (up to Infinity)
- When under high-load, even not `stream file`, headers duplicated (1-5x times)
- When testing with `wrk` this issue happens too
- If as client using `Safari`, issue happening less than `Chrome`

More info [here](https://github.com/sifrr/sifrr/issues/280) and [here](https://github.com/dalisoft/nanoexpress/issues/63)

**Comment by zorro-fr24** [comment]
I just wanted to point out that browsers aren't the only use case here.

A real-world use case would be when you use uws in an api gateway to interconnect applications and services: pipelining allows you to easily enable batch queries without having to implement any special service behaviour.

**Comment by aadityataparia** [comment]
Agreeing with @zorro-fr24. This is a normal use case for microservices where you have a client facing aggregator connecting to other services running uwebsockets servers.

**Comment by alexhultman** [comment]
Pipelining works if you don't stream. So if you send JSON of a handful KB it will work just fine. It's only the streaming that doesn't work, and streaming is something you do with large data such as streaming a video or something like that. You don't care for pipelining when streaming a video.

However, yes, it is a feature that should be fixed. It's not super critical though.

**Comment by alexhultman** [comment]
I've done some thinking and I remember now why this never was done;

Http 1.1 pipelining is not really that good. It has head of line blocking problems and doesn't really guarantee any kind of improvement in terms of batching. No modern browser use it, and it doesn't fit in with the efficient data flow of uWS. If you want better batching against some proxy, have it open 10 connections rather than pipeline 10 requests on one connection. Then you'll have 10 properly isolated channels at negligible cost.

Http 2 has good pipelining support but uWS is not an Http 2 server.

**Comment by alexhultman** [comment]
The reason you get messy responses as reported in this issue is a bug that should be fixed, but pipelining will not be. (Pipelining still works for all requests you respond to immediately)

**Comment by alexhultman** [comment]
The issue of duplicated headers should be fixed now, closing.

**Comment by dalisoft** [comment]
@alexhultman Is there any plan to merge latest uWebSockets to uWebSockets.js repository and release v0.17 or v0.17 still in progress?

**Comment by alexhultman** [comment]
Yes I'm just finishing up by fixing a few bugs
